import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { CheckCircle2, ShieldCheck, Activity, Info, Smartphone, MapPin, User, AlertTriangle, Network } from 'lucide-react';
import { cn } from '../lib/utils';

const TIMELINE_DATA = [
  { time: '0.00s', sentiment: 0.2, stress: 0.1 },
  { time: '5.00s', sentiment: 0.8, stress: 0.3 },
  { time: '10.00s', sentiment: 0.5, stress: 0.15 },
  { time: '15.00s', sentiment: 0.7, stress: 0.4 },
  { time: '20.00s', sentiment: 0.3, stress: 0.2 },
  { time: '25.00s', sentiment: 0.6, stress: 0.6 },
  { time: '30.00s', sentiment: 0.4, stress: 0.4 },
  { time: '35.00s', sentiment: 0.8, stress: 0.1 },
  { time: '40.00s', sentiment: 0.5, stress: 0.15 },
  { time: '45.00s', sentiment: 0.6, stress: 0.2 },
];

export default function ClaimDeepDive() {
  return (
    <div className="space-y-8 pb-12">
      {/* Hero Section */}
      <section className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="bg-primary-container text-on-primary-container px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase">FAST-TRACK</span>
            <span className="text-on-surface-variant font-medium text-sm">#CLM-99283-X</span>
          </div>
          <h2 className="text-3xl font-extrabold tracking-tight">Physiological Risk Deep-Dive</h2>
          <p className="text-on-surface-variant mt-1 max-w-2xl text-sm leading-relaxed">
            Detailed intelligence report on claim integrity using acoustic telemetry and graph node correlation. Analysis generated by Cypher Intelligence Engine.
          </p>
        </div>
        <div className="flex gap-3 w-full md:w-auto">
          <button className="flex-1 md:flex-initial px-4 py-2 bg-surface-container-high text-on-surface font-semibold text-sm rounded-lg hover:bg-on-surface/10 transition-colors">
            Archive Case
          </button>
          <button className="flex-1 md:flex-initial px-4 py-2 bg-primary text-on-primary-container bg-primary-container font-bold text-sm rounded-lg hover:bg-primary-container/80 transition-colors flex items-center justify-center gap-2">
            <CheckCircle2 className="w-4 h-4" />
            Approve Claim
          </button>
        </div>
      </section>

      {/* Metrics Grid */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-surface-container-lowest p-6 rounded-xl shadow-sm">
          <div className="flex justify-between items-start mb-4">
            <p className="text-sm font-semibold text-on-surface-variant">Trust Score</p>
            <ShieldCheck className="w-4 h-4 text-primary" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-extrabold tracking-tighter">94.2</span>
            <span className="text-sm text-primary font-bold">/ 100</span>
          </div>
          <div className="mt-4 w-full bg-surface-container-low h-1.5 rounded-full overflow-hidden">
            <div className="bg-primary h-full w-[94.2%]"></div>
          </div>
          <p className="mt-4 text-[0.6875rem] text-on-surface-variant uppercase tracking-widest font-bold">Historical baseline: 82.0</p>
        </div>

        <div className="bg-surface-container-lowest p-6 rounded-xl shadow-sm">
          <div className="flex justify-between items-start mb-4">
            <p className="text-sm font-semibold text-on-surface-variant">Distress Score</p>
            <Activity className="w-4 h-4 text-error" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-extrabold tracking-tighter">12.8</span>
            <span className="text-sm text-error font-bold">/ 100</span>
          </div>
          <div className="mt-4 w-full bg-surface-container-low h-1.5 rounded-full overflow-hidden">
            <div className="bg-error h-full w-[12.8%]"></div>
          </div>
          <p className="mt-4 text-[0.6875rem] text-on-surface-variant uppercase tracking-widest font-bold">Critical Threshold: 45.0</p>
        </div>

        <div className="bg-surface-container-lowest p-6 rounded-xl shadow-sm">
          <div className="flex justify-between items-start mb-4">
            <p className="text-sm font-semibold text-on-surface-variant">Confidence Coeff.</p>
            <Activity className="w-4 h-4 text-on-surface-variant" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-extrabold tracking-tighter">0.98</span>
            <span className="text-sm text-on-surface-variant font-bold">σ</span>
          </div>
          <div className="mt-4 w-full bg-surface-container-low h-1.5 rounded-full overflow-hidden">
            <div className="bg-on-surface-variant h-full w-[98%]"></div>
          </div>
          <p className="mt-4 text-[0.6875rem] text-on-surface-variant uppercase tracking-widest font-bold">Data completeness: 100%</p>
        </div>
      </section>

      {/* Graph & Logic Grid */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-8 bg-surface-container-lowest rounded-xl p-8 shadow-sm relative min-h-[400px]">
          <h3 className="text-lg font-bold mb-6 flex items-center gap-2">
            <Network className="w-5 h-5 text-primary" />
            Entity Correlation Graph
          </h3>
          
          <div className="relative w-full h-[300px] flex items-center justify-center bg-surface-container-low/30 rounded-lg border border-on-surface/5">
            {/* Simulated Graph Nodes */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
              <div className="w-16 h-16 bg-primary-container rounded-full flex items-center justify-center border-4 border-surface shadow-sm ring-1 ring-primary/10">
                <User className="w-8 h-8 text-primary" />
              </div>
              <span className="mt-2 text-[0.6875rem] font-bold uppercase tracking-widest text-primary">Policy Holder</span>
            </div>

            <div className="absolute top-[20%] left-[30%] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
              <div className="w-12 h-12 bg-primary-container rounded-full flex items-center justify-center border-2 border-surface ring-1 ring-primary/10">
                <Smartphone className="w-6 h-6 text-primary" />
              </div>
              <span className="mt-2 text-[0.6875rem] font-medium text-on-surface-variant">Device Hash</span>
            </div>

            <div className="absolute top-[20%] left-[70%] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center group">
              <div className="w-12 h-12 bg-error-container rounded-full flex items-center justify-center border-2 border-surface ring-1 ring-error/20">
                <AlertTriangle className="w-6 h-6 text-on-error-container" />
              </div>
              <span className="mt-2 text-[0.6875rem] font-bold text-error uppercase">Fraud Match</span>
            </div>

            <div className="absolute top-[80%] left-[50%] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
              <div className="w-12 h-12 bg-primary-container rounded-full flex items-center justify-center border-2 border-surface ring-1 ring-primary/10">
                <MapPin className="w-6 h-6 text-primary" />
              </div>
              <span className="mt-2 text-[0.6875rem] font-medium text-on-surface-variant">Incident Loc</span>
            </div>

            {/* SVG Lines */}
            <svg className="absolute inset-0 w-full h-full pointer-events-none opacity-20">
              <line x1="50%" y1="50%" x2="30%" y2="20%" stroke="#566342" strokeWidth="1" strokeDasharray="4" />
              <line x1="50%" y1="50%" x2="70%" y2="20%" stroke="#9e422c" strokeWidth="1" strokeDasharray="4" />
              <line x1="50%" y1="50%" x2="50%" y2="80%" stroke="#566342" strokeWidth="1" strokeDasharray="4" />
            </svg>
          </div>

          <div className="mt-6 flex flex-wrap gap-6 items-center border-t border-on-surface/5 pt-6">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-primary-container"></div>
              <span className="text-xs text-on-surface-variant">Validated Entity</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-error-container"></div>
              <span className="text-xs text-on-surface-variant">Risk Flag</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-8 h-[1px] bg-on-surface/20 border-t border-dashed"></div>
              <span className="text-xs text-on-surface-variant">Low Latency Link</span>
            </div>
          </div>
        </div>

        <div className="lg:col-span-4 space-y-6">
          <div className="bg-surface-container-lowest rounded-xl p-6 shadow-sm">
            <h4 className="text-sm font-bold uppercase tracking-wider text-on-surface-variant mb-4">Intelligence Logic</h4>
            <ul className="space-y-4">
              <li className="flex gap-3">
                <CheckCircle2 className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                <p className="text-sm leading-relaxed">Acoustic telemetry detected genuine physiological stress markers during first-response call.</p>
              </li>
              <li className="flex gap-3">
                <CheckCircle2 className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                <p className="text-sm leading-relaxed">Device metadata confirms physical presence at incident location within 0.02s of timestamp.</p>
              </li>
              <li className="flex gap-3">
                <Info className="w-4 h-4 text-error shrink-0 mt-0.5" />
                <p className="text-sm leading-relaxed text-on-surface-variant italic">Secondary entity flag triggered due to shared wallet ID, but dismissed via behavioral override.</p>
              </li>
            </ul>
          </div>

          <div className="bg-primary text-on-primary-container bg-primary-container rounded-xl p-6">
            <h4 className="text-[10px] font-bold uppercase tracking-widest mb-2 opacity-80">System Recommendation</h4>
            <p className="text-xl font-bold leading-tight">Proceed with Instant Liquidation.</p>
            <p className="text-xs mt-3 opacity-70 leading-relaxed">Risk parameters are within the acceptable variance for Clinical Node 01 autonomy.</p>
          </div>
        </div>
      </section>

      {/* Signal Timeline */}
      <section className="bg-surface-container-lowest rounded-xl p-8 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h3 className="text-lg font-bold">Signal Timeline Correlation</h3>
            <p className="text-sm text-on-surface-variant">Sentiment vs. Physiological Stress over 45s transcript duration</p>
          </div>
          <div className="flex gap-4">
            <div className="flex items-center gap-2">
              <span className="w-3 h-0.5 bg-primary"></span>
              <span className="text-[0.6875rem] font-bold uppercase tracking-wider">Sentiment</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-3 h-0.5 bg-error"></span>
              <span className="text-[0.6875rem] font-bold uppercase tracking-wider">Stress Level</span>
            </div>
          </div>
        </div>

        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={TIMELINE_DATA}>
              <CartesianGrid vertical={false} strokeDasharray="3 3" stroke="#f1f4f6" />
              <XAxis 
                dataKey="time" 
                axisLine={false} 
                tickLine={false} 
                tick={{ fontSize: 10, fill: '#586064' }} 
                dy={10}
              />
              <Tooltip 
                contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}
              />
              <Line type="monotone" dataKey="sentiment" stroke="#566342" strokeWidth={2} dot={false} />
              <Line type="monotone" dataKey="stress" stroke="#9e422c" strokeWidth={2} dot={false} strokeOpacity={0.6} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        <div className="mt-12 grid grid-cols-2 md:grid-cols-4 gap-4 pt-6 border-t border-on-surface/5">
          <div className="flex flex-col">
            <span className="text-[0.625rem] text-on-surface-variant uppercase font-bold tracking-widest">Peak Sentiment</span>
            <span className="text-lg font-bold text-primary">0.92</span>
          </div>
          <div className="flex flex-col">
            <span className="text-[0.625rem] text-on-surface-variant uppercase font-bold tracking-widest">Acoustic Jitter</span>
            <span className="text-lg font-bold">2.4ms</span>
          </div>
          <div className="flex flex-col">
            <span className="text-[0.625rem] text-on-surface-variant uppercase font-bold tracking-widest">Linguistic Cohesion</span>
            <span className="text-lg font-bold">High</span>
          </div>
          <div className="flex flex-col">
            <span className="text-[0.625rem] text-on-surface-variant uppercase font-bold tracking-widest">Authenticity Confidence</span>
            <span className="text-lg font-bold text-primary">99.1%</span>
          </div>
        </div>
      </section>
    </div>
  );
}
